version: '3.8'

networks:
  minha-rede:
    driver: bridge

services:
  discovery-meus-macros:
    image: meu-discovery-meus-macros-img
    build:
      context: ./discovery-meus-macros
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - minha-rede

  gateway-meus-macros:
    image: meu-gateway-meus-macros-img
    build:
      context: ./gateway-meus-macros
      dockerfile: Dockerfile
    depends_on:
      - discovery-meus-macros
    ports:
      - "8082:8082"
    networks:
      - minha-rede  # Conectando na mesma rede
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-meus-macros:8081/eureka

