version: '3.8'

networks:
  minha-rede:
    driver: bridge

services:
  discovery-meus-macros:
    image: meu-discovery-meus-macros-img
    build:
      context: ./discovery-meus-macros
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - minha-rede

  gateway-meus-macros:
    image: meu-gateway-meus-macros-img
    build:
      context: ./gateway-meus-macros
      dockerfile: Dockerfile
    depends_on:
      - discovery-meus-macros
    ports:
      - "8082:8082"
    networks:
      - minha-rede
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-meus-macros:8081/eureka

  ai-meus-macros:
    image: ai-meus-macros-img
    build:
      context: ./ai-meus-macros
      dockerfile: Dockerfile
      args:
        OPENAI_API_KEY: "chave-fake"
    depends_on:
      - gateway-meus-macros
    networks:
      - minha-rede
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-meus-macros:8081/eureka
      OPENAI_API_KEY: ${OPENAI_API_KEY}

  auth-meus-macros:
    image: auth-meus-macros-img
    build:
      context: ./auth-meus-macros
      dockerfile: Dockerfile
    depends_on:
      - gateway-meus-macros
      - auth-meus-macros-db
    networks:
      - minha-rede
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-meus-macros:8081/eureka
      SPRING_DATASOURCE_URL: jdbc:mysql://auth-meus-macros-db:3306/auth_meus_macros?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

  auth-meus-macros-db:
    image: mysql:8.0
    container_name: mysql_auth_meus_macros
    networks:
      - minha-rede
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: auth_meus_macros
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - auth-meus-macros-data:/var/lib/mysql

  macros-calculator-meus-macros:
    image: macros-calculator-meus-macros-img
    build:
      context: ./macros-calculator-meus-macros
      dockerfile: Dockerfile
    depends_on:
      - gateway-meus-macros
      - macros-calculator-meus-macros-db
    networks:
      - minha-rede
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-meus-macros:8081/eureka
      SPRING_DATASOURCE_URL: jdbc:mysql://macros-calculator-meus-macros-db:3306/macros_calculator_meus_macros?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

  macros-calculator-meus-macros-db:
    image: mysql:8.0
    container_name: mysql_macros_calculator_meus_macros
    networks:
      - minha-rede
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: macros_calculator_meus_macros
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - macros-calculator-meus-macros-data:/var/lib/mysql

  email-meus-macros:
    image: email-meus-macros-img
    build:
      context: ./email-meus-macros
      dockerfile: Dockerfile
    depends_on:
      - gateway-meus-macros
    networks:
      - minha-rede
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-meus-macros:8081/eureka

  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: rabbitmq
    networks:
      - minha-rede
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  auth-meus-macros-data:
  macros-calculator-meus-macros-data:
