version: '3.8'

networks:
  minha-rede:
    driver: bridge

services:
  discovery-meus-macros:
    image: meu-discovery-meus-macros-img
    build:
      context: ./discovery-meus-macros
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - minha-rede

  gateway-meus-macros:
    image: meu-gateway-meus-macros-img
    build:
      context: ./gateway-meus-macros
      dockerfile: Dockerfile
    depends_on:
      - discovery-meus-macros
    ports:
      - "8082:8082"
    networks:
      - minha-rede  # Conectando na mesma rede
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-meus-macros:8081/eureka

  ai-meus-macros:
    image: ai-meus-macros-img
    build:
      context: ./ai-meus-macros
      dockerfile: Dockerfile
      args:
        OPENAI_API_KEY: "chave-fake"  # Passando chave fake no build
    depends_on:
      - gateway-meus-macros
    networks:
      - minha-rede
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-meus-macros:8081/eureka
      OPENAI_API_KEY: ${OPENAI_API_KEY}

  auth-meus-macros:
    image: auth-meus-macros-img
    build:
      context: ./auth-meus-macros
      dockerfile: Dockerfile
    depends_on:
      - gateway-meus-macros
      - auth-meus-macros-db
    networks:
      - minha-rede
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-meus-macros:8081/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-meus-macros-db:5432/auth_meus_macros
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
  auth-meus-macros-db:
    image: postgres:16
    container_name: postgres_auth_meus_macros
    networks:
      - minha-rede
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_meus_macros
    volumes:
      - auth-meus-macros-data:/var/lib/postgresql/data
  macros-calculator-meus-macros:
    image: macros-calculator-meus-macros-img
    build:
      context: ./macros-calculator-meus-macros
      dockerfile: Dockerfile
    depends_on:
      - gateway-meus-macros
      - macros-calculator-meus-macros-db
    networks:
      - minha-rede
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-meus-macros:8081/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://macros-calculator-meus-macros-db:5432/macros-calculator_meus_macros
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
  macros-calculator-meus-macros-db:
    image: postgres:16
    container_name: postgres_macros-calculator_meus_macros
    networks:
      - minha-rede
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: macros-calculator_meus_macros
    volumes:
      - macros-calculator-meus-macros-data:/var/lib/postgresql/data

volumes:
  auth-meus-macros-data:
  macros-calculator-meus-macros-data: