CREATE TABLE goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_uuid UUID NOT NULL,
    date TIMESTAMP NOT NULL,
    calories INTEGER NOT NULL,
    protein_percentage INTEGER NOT NULL,
    carbohydrates_percentage INTEGER NOT NULL,
    fat_percentage INTEGER NOT NULL
);
